import { firstValueFrom } from 'rxjs';
import { Injectable, signal, computed, inject, effect } from '@angular/core';
import { CustomerService } from '../../services/customer.service';
import { Customer, CreateAddressRequest, CreateCreditCardRequest } from '../../models/customer';
import { NotificationService } from '../../core/notification/notification.service';

export interface CustomerState {
  customer: Customer | null;
  loading: boolean;
  error: string | null;
}

@Injectable({
  providedIn: 'root'
})
export class CustomerStore {
  private readonly customerService = inject(CustomerService);
  private readonly notificationService = inject(NotificationService);

  // Private state
  private readonly state = signal<CustomerState>({
    customer: null,
    loading: false,
    error: null
  });

  // Public selectors
  readonly customer = computed(() => this.state().customer);
  readonly loading = computed(() => this.state().loading);
  readonly error = computed(() => this.state().error);

  // Computed selectors
  readonly hasCustomer = computed(() => !!this.state().customer);
  readonly customerName = computed(() => {
    const cust = this.state().customer;
    return cust ? `${cust.first_name || ''} ${cust.last_name || ''}`.trim() : '';
  });
  readonly customerEmail = computed(() => this.state().customer?.email || '');
  readonly addresses = computed(() => {
    const addresses = this.state().customer?.addresses || [];
    return addresses;
  });
  readonly creditCards = computed(() => {
    const creditCards = this.state().customer?.credit_cards || [];
    return creditCards;
  });
  readonly defaultShippingAddress = computed(() => {
    const customer = this.state().customer;
    if (!customer?.default_shipping_address_id || !customer.addresses) return null;
    return customer.addresses.find(addr => addr.address_id === customer.default_shipping_address_id);
  });

  readonly defaultBillingAddress = computed(() => {
    const customer = this.state().customer;
    if (!customer?.default_billing_address_id || !customer.addresses) return null;
    return customer.addresses.find(addr => addr.address_id === customer.default_billing_address_id);
  });

  readonly defaultCreditCard = computed(() => {
    const customer = this.state().customer;
    if (!customer?.default_credit_card_id || !customer.credit_cards) return null;
    return customer.credit_cards.find(card => card.card_id === customer.default_credit_card_id);
  });

  // Actions
  async loadCustomer(email: string): Promise<void> {
    if (!email) return;
    this.setState({ loading: true, error: null });

    try {
      const customer = await firstValueFrom(this.customerService.getCustomer(email));
        if (customer) {
          this.setState({ customer, loading: false });
        } else {
          // Customer not found - return null without error, let caller decide what to do
          this.setState({ customer: null, loading: false });
        }
    } catch (error) {
      this.setState({ 
        loading: false, 
        error: 'Failed to load customer data' 
      });
    }
  }

  async createCustomerFromAuth(userData: any): Promise<void> {
    if (!userData?.email) return;

    const newCustomer: Customer = {
      customer_id: '', // Will be generated by backend
      user_name: userData.preferred_username || userData.email || '',
      email: userData.email,
      first_name: userData.given_name,
      last_name: userData.family_name,
      phone: '',
      default_shipping_address_id: null,
      default_billing_address_id: null,
      default_credit_card_id: null,
      customer_since: new Date().toISOString(),
      customer_status: 'active',
      status_date_time: new Date().toISOString(),
      addresses: [],
      credit_cards: [],
      status_history: []
    };

    try {
      const savedCustomer = await firstValueFrom(this.customerService.createCustomer(newCustomer));
      this.setState({ customer: savedCustomer, loading: false });
      this.notificationService.showSuccess('Customer profile created successfully');
    } catch (error) {
      this.setState({ 
        loading: false, 
        error: 'Failed to create customer profile' 
      });
    }
  }

  async updateCustomer(customer: Customer): Promise<void> {
    this.setState({ loading: true, error: null });

    try {
      const updatedCustomer = await firstValueFrom(this.customerService.updateCustomer(customer));
      this.setState({ customer: updatedCustomer, loading: false });
      this.notificationService.showSuccess('Profile updated successfully');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to update profile'
      });
    }
  }

  async patchCustomer(customerId: string, updates: Partial<Customer>): Promise<void> {
    this.setState({ loading: true, error: null });

    try {
      const currentCustomer = this.state().customer;
      const updatedCustomer = await firstValueFrom(this.customerService.patchCustomer(customerId, updates));

      // API now returns complete customer objects with all fields
      // Validate response completeness, fallback to merge if incomplete
      if (this.isCompleteCustomerResponse(updatedCustomer)) {
        this.setState({ customer: updatedCustomer, loading: false });
      } else {
        let mergedCustomer: Customer;
        if (currentCustomer) {
          mergedCustomer = Object.assign({}, currentCustomer, updatedCustomer) as Customer;
        } else {
          mergedCustomer = updatedCustomer as unknown as Customer;
        }
        this.setState({ customer: mergedCustomer, loading: false });
      }

      this.notificationService.showSuccess('Profile updated successfully');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to update profile'
      });
    }
  }

  async addAddress(address: CreateAddressRequest): Promise<void> {
    const currentCustomer = this.state().customer;
    if (!currentCustomer?.customer_id) return;

    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.addAddress(currentCustomer.customer_id, address));
      // Reload customer data to get updated addresses with proper IDs
      await this.loadCustomer(currentCustomer.email || '');
      this.notificationService.showSuccess('Address added successfully');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to add address'
      });
    }
  }

  async updateAddress(addressId: string, address: any): Promise<void> {
    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.updateAddress(addressId, address));
      // Reload customer data to get updated addresses
      const currentCustomer = this.state().customer;
      if (currentCustomer?.email) {
        await this.loadCustomer(currentCustomer.email);
      }
      this.notificationService.showSuccess('Address updated successfully');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to update address'
      });
    }
  }

  async deleteAddress(addressId: string): Promise<void> {
    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.deleteAddress(addressId));
      const currentCustomer = this.state().customer;
      if (currentCustomer?.addresses) {
        const updatedAddresses = currentCustomer.addresses.filter(
          addr => addr.address_id !== addressId
        );
        this.setState({ 
          customer: { ...currentCustomer, addresses: updatedAddresses },
          loading: false 
        });
        this.notificationService.showSuccess('Address deleted successfully');
      }
    } catch (error) {
      this.setState({ 
        loading: false, 
        error: 'Failed to delete address' 
      });
    }
  }

  async addCreditCard(card: CreateCreditCardRequest): Promise<void> {
    const currentCustomer = this.state().customer;
    if (!currentCustomer?.customer_id) return;

    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.addCreditCard(currentCustomer.customer_id, card));
      // Reload customer data to get updated credit cards with proper IDs
      await this.loadCustomer(currentCustomer.email || '');
      this.notificationService.showSuccess('Credit card added successfully');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to add credit card'
      });
    }
  }

  async updateCreditCard(cardId: string, card: any): Promise<void> {
    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.updateCreditCard(cardId, card));
      // Reload customer data to get updated credit cards
      const currentCustomer = this.state().customer;
      if (currentCustomer?.email) {
        await this.loadCustomer(currentCustomer.email);
      }
      this.notificationService.showSuccess('Credit card updated successfully');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to update credit card'
      });
    }
  }

  async deleteCreditCard(cardId: string): Promise<void> {
    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.deleteCreditCard(cardId));
      const currentCustomer = this.state().customer;
      if (currentCustomer?.credit_cards) {
        const updatedCards = currentCustomer.credit_cards.filter(
          card => card.card_id !== cardId
        );
        this.setState({
          customer: { ...currentCustomer, credit_cards: updatedCards },
          loading: false
        });
        this.notificationService.showSuccess('Credit card deleted successfully');
      }
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to delete credit card'
      });
    }
  }

  // Default management methods
  async setDefaultShippingAddress(addressId: string): Promise<void> {
    const currentCustomer = this.state().customer;
    if (!currentCustomer?.customer_id) return;

    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.setDefaultShippingAddress(currentCustomer.customer_id, addressId));
      // Reload customer to get updated defaults
      await this.loadCustomer(currentCustomer.email || '');
      this.notificationService.showSuccess('Default shipping address updated');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to set default shipping address'
      });
    }
  }

  async setDefaultBillingAddress(addressId: string): Promise<void> {
    const currentCustomer = this.state().customer;
    if (!currentCustomer?.customer_id) return;

    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.setDefaultBillingAddress(currentCustomer.customer_id, addressId));
      // Reload customer to get updated defaults
      await this.loadCustomer(currentCustomer.email || '');
      this.notificationService.showSuccess('Default billing address updated');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to set default billing address'
      });
    }
  }

  async setDefaultCreditCard(cardId: string): Promise<void> {
    const currentCustomer = this.state().customer;
    if (!currentCustomer?.customer_id) return;

    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.setDefaultCreditCard(currentCustomer.customer_id, cardId));
      // Reload customer to get updated defaults
      await this.loadCustomer(currentCustomer.email || '');
      this.notificationService.showSuccess('Default credit card updated');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to set default credit card'
      });
    }
  }

  async clearDefaultShippingAddress(): Promise<void> {
    const currentCustomer = this.state().customer;
    if (!currentCustomer?.customer_id) return;

    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.clearDefaultShippingAddress(currentCustomer.customer_id));
      // Reload customer to get updated defaults
      await this.loadCustomer(currentCustomer.email || '');
      this.notificationService.showSuccess('Default shipping address cleared');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to clear default shipping address'
      });
    }
  }

  async clearDefaultBillingAddress(): Promise<void> {
    const currentCustomer = this.state().customer;
    if (!currentCustomer?.customer_id) return;

    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.clearDefaultBillingAddress(currentCustomer.customer_id));
      // Reload customer to get updated defaults
      await this.loadCustomer(currentCustomer.email || '');
      this.notificationService.showSuccess('Default billing address cleared');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to clear default billing address'
      });
    }
  }

  async clearDefaultCreditCard(): Promise<void> {
    const currentCustomer = this.state().customer;
    if (!currentCustomer?.customer_id) return;

    this.setState({ loading: true, error: null });

    try {
      await firstValueFrom(this.customerService.clearDefaultCreditCard(currentCustomer.customer_id));
      // Reload customer to get updated defaults
      await this.loadCustomer(currentCustomer.email || '');
      this.notificationService.showSuccess('Default credit card cleared');
    } catch (error) {
      this.setState({
        loading: false,
        error: 'Failed to clear default credit card'
      });
    }
  }

  clearError(): void {
    this.setState({ error: null });
  }

  // Private helper methods
  private setState(partialState: Partial<CustomerState>): void {
    this.state.update(currentState => ({ ...currentState, ...partialState }));
  }

  private isCompleteCustomerResponse(customer: any): customer is Customer {
    return customer &&
      typeof customer.customer_id === 'string' &&
      typeof customer.user_name === 'string' &&
      typeof customer.email === 'string' &&
      typeof customer.first_name === 'string' &&
      typeof customer.last_name === 'string' &&
      typeof customer.phone === 'string' &&
      // Check default fields are present (can be null)
      customer.hasOwnProperty('default_shipping_address_id') &&
      customer.hasOwnProperty('default_billing_address_id') &&
      customer.hasOwnProperty('default_credit_card_id') &&
      typeof customer.customer_since === 'string' &&
      typeof customer.customer_status === 'string' &&
      typeof customer.status_date_time === 'string' &&
      Array.isArray(customer.addresses) &&
      Array.isArray(customer.credit_cards) &&
      Array.isArray(customer.status_history);
  }
}